### ISSUE TITLE
Sort doesn't work in FF 16.02, when <td> has a subelement such as <a href>

### ISSUE THREAD

**Issue by jackiekazil** [tristen/tablesort#9]
It throws the following error: 

```
TypeError: this.getInnerText is not a function
[Break On This Error]   
str += this.getInnerText(cs[i]);
```

It works fine in Chrome & IE 8, which I checked briefly. I am in the process of creating a fix that will traverse the nodes in the cell until it reaches text, then return that text. 

Sound good?
